### PR TITLE
Fix bug: plugin scripts being added every page load

### LINKED ISSUE #81: Plugin scripts being appended multiple times
`<script>` tags for plugins are getting appended with every re-render of `App.js`

This does not seem to affect performance or functionality, but should still be addressed sometime

image

### PR DESCRIPTION
**Pull request by garrettluu**
Closes #81.

Plugins are still registered with every rerender of App.js. Currently, the function call looks like this:
```js
useEffect(() => {
    registerDefaultPlugins();
});
```
Changing it to this would theoretically fix the problem, since it would only be called on the first render:
```js
useEffect(() => {
    registerDefaultPlugins();
}, []);
```
but for some reason the plugins all become undefined and everything breaks. (Is this bug even worth fixing?)
image

### CODE REVIEW

**Comment by barronwei** [comment]
What do you mean by the plugins become undefined?

**Comment by barronwei** [comment]
Can you try doing

```
  useEffect(() => {
    importDefaultPlugins();
    registerDefaultPlugins();
  }, []);
```

**Comment by garrettluu** [comment]
Probably gonna close this once #113 gets done

File: src/plugins/plugins-list.js [hunk 1]
```diff
@@ -74,3 +76,23 @@ export const presets = {
     defaultConfig: {},
   },
 };
+
+const pluginMap = new Map([
```
Comment (garrettluu) [inline src/plugins/plugins-list.js:80]: Any reason for using `Map` instead of just using a js object?
```js
{
  "plugin-name": "pluginName",
  //...
}
```

File: src/plugins/plugins-list.js [hunk 2]
```diff
@@ -74,3 +76,23 @@ export const presets = {
...
+  ["babel-plugin-polyfill-regenerator", "babelPluginPolyfillRegenerator"],
+]);
+
+export function addDefaultPlugins() {
+  Object.keys(plugins).forEach(pluginName => {
+    const script = document.createElement("script");
+    script.src = plugins[pluginName].fileLocation;
+    script.async = true;
+    script.addEventListener("load", () => {
+      Babel.registerPlugin(pluginName, window[pluginMap.get(pluginName)]);
```
Comment (garrettluu) [inline src/plugins/plugins-list.js:94]: 🤯

**Review by garrettluu — COMMENTED** [review]
Looks good to me! Thanks for finishing this PR for me 😅

File: src/plugins/plugins-list.js (hunk 1 above)
Comment (penguingovernor) [reply src/plugins/plugins-list.js:80]: No concrete reason other than just using key-value pairs! (:

**Review by wlawt — APPROVED** [review]
lgtm I don't see the scripts being re-added!
